### ISSUE TITLE
编译成electron:build之后，没有图片、图标、音乐资源显示出来

### ISSUE THREAD

**Issue by maypu** [bknds/B726Desktop#1]
npm version: 6.14.2
mode version: 12.22.1
编译成功后，双击运行软件但不显示图片、图标、音乐资源，界面基本处于空白状态，是咪咕接口的问题？

**Comment by bknds** [comment]
您可尝试先在本地跑一下这个项目
https://github.com/BrickPickerOrg/BkndsApi
